### PR TITLE
Fix/score

### PR DESCRIPTION
**Pull request by antoinegauvain**

### CODE REVIEW

**Comment by aseure** [comment]
We can use a `map` instead of a `slice` for the `seen` variable. It would be more efficient and we will avoid to write our own function to check if the element is there or not.

**Comment by antoinegauvain** [comment]
I agree it's better not to code our own function, but about your performance thing, unless you plan having 100 words filenames, I doubt we will ever see the benefit.

http://www.darkcoding.net/software/go-slice-search-vs-map-lookup/

**Comment by antoinegauvain** [comment]
(by the way I compiled and tested, it works)

**Comment by aseure** [comment]
Thanks for the insightful link. I agree with you on the practical point of view. 

However, efficiency apart, I still prefer the map-based implementation as it avoids to add a function.

**Comment by aseure** [comment]
👍

For your information, you can also checked the presence of an element in a `map` by using:

```go
if _, ok := seen[k1]; ok {
    // Do something
}
```

Here you ignoring the value returned by using the `_` (which is the `0` value of the type when the element is not found) and `ok` is a boolean that tells you if the key was found or not. In your case, since you're storing booleans, the `0` value that you're getting when the element is missing is `false`, which is fine.

**Comment by antoinegauvain** [comment]
actually it does not work, I misunderstood the output of the binary for a success, but it's only the output when it receives a command
on the merged version the score will always return 0

**Pull request merged**
